# -*- coding: utf-8 -*-
"""Introdução a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FlScuDfbSVfzkmNoaejJY9PCDhrXq44G
"""

import pandas as pd
notas = pd.read_csv('ratings.csv')
notas.head()

notas.shape

notas.columns = ['usuarioId', 'filmeId', 'nota', 'momento']
notas.head()

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

notas.nota

notas.nota.head()

notas.nota.plot(kind='hist')

notas.nota.median()

notas.nota.describe()

import seaborn as sns
sns.boxplot(notas.nota)

filmes = pd.read_csv('movies.csv')
filmes.columns = ["filmeId", "titulo", "generos"]
notas.query("filmeId==1").nota

"""Olhando os filmes"""

notas.query('filmeId==1').nota.mean()

notas.query('filmeId==2').nota.mean()

media_por_filme = notas.groupby('filmeId').nota.mean()
media_por_filme.head()

media_por_filme.plot(kind="hist")

sns.boxplot(media_por_filme)

media_por_filme.describe()

sns.distplot(media_por_filme)

sns.distplot(media_por_filme, bins=10)

import matplotlib.pyplot as plt
plt.hist(media_por_filme)
plt.title("Histograma das medias dos filmes")

